[workspace]
members = [
    "visualize",
]

[package]
name = "plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
visualize = { path = "visualize" }
statrs = "0.16.0"
mentat = "0.0.4"
itertools-num = "0.1.3"
