name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fmt:
    name: fmt check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: clippy check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
